-- Your SQL goes here
CREATE TABLE files (
    id SERIAL PRIMARY KEY,
    file_path VARCHAR(512) UNIQUE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT 'now',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT 'now'
);

CREATE TABLE images (
    id SERIAL PRIMARY KEY,
    uploaded_by INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    size_200 INTEGER REFERENCES files(id) ON DELETE CASCADE NOT NULL,
    size_400 INTEGER REFERENCES files(id) ON DELETE CASCADE NOT NULL,
    size_800 INTEGER REFERENCES files(id) ON DELETE CASCADE,
    size_1200 INTEGER REFERENCES files(id) ON DELETE CASCADE,
    size_full INTEGER REFERENCES files(id) ON DELETE CASCADE NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    ratio REAL NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT 'now',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT 'now'
);

CREATE TABLE unprocessed_images (
    id SERIAL PRIMARY KEY,
    uploaded_by INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    image_file INTEGER REFERENCES files(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT 'now',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT 'now'
);
